### ISSUE TITLE
Any plan for chronograf open source?

### ISSUE THREAD

**Issue by xiocode** [influxdata/chronograf-docker#8]
Hi, i use TICK for monitoring now, and i found chronograf is only repo not open source. i want make some feature on this repo, so can your guys tell me what plan for chronograf now?

**Comment by pauldix** [comment]
We don't have plans to open source it right now. For an open source graphing option take a look at Grafana: http://grafana.org/

**Comment by smparkes** [comment]
From https://news.ycombinator.com/item?id=10706210:

> We'll definitely be open sourcing some things from Chronograf and it's free to use.

Any details on that?
